[tool.poetry]
name = "tinybee"
version = "0.1.0"
description = "A tiny aligner for dualtext alignment"
authors = ["ffreemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/tinybee-aligner"

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "^3.7"
=======
python = "^3.6.1"
>>>>>>> 0fcdf88ebab8c0e68e09d8b3dc29b02b675c8a31
logzero = "^1.6.3"
polyglot = "^16.7.4"
sentence-splitter = "^1.4"
more-itertools = "^8.6.0"
joblib = "^1.0.0"
cchardet = "^2.1.7"
tqdm = "^4.56.0"
statsmodels = "^0.12.1"
httpx = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
